<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<style>
   /* reset */
    #ratepay-main-cont, #ratepay-main-cont div, #ratepay-main-cont span, #ratepay-main-cont p, #ratepay-main-cont input, #ratepay-main-cont select, #ratepay-main-cont h2, #ratepay-main-cont table, #ratepay-main-cont td {
        font: 13px  Arial,"Helvetica Neue",Helvetica,sans-serif;
        line-height: 17px;
        text-align: left;
    }

    /* RatePAY Calculator */
    .ratepay-Left {
        text-align: left;
    }
    
    .ratepay-ClearFix {
        clear: both;
        line-height: 1px;
        height: 1px;
    }

    #ratepay-main-cont {
        width: 472px !important;
        margin: 0 auto;
        vertical-align: middle;
    }

    #ratepay-main-cont input.ratepay-input-button {
        width:164px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 5px;
        right:5px;
        margin-left: 15px;
    }
    #ratepay-main-cont input.ratepay-input-button2 {
        width:164px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 5px;
        right:5px;
    }
    #ratepay-main-cont input.ratepay-input-button:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #ratepay-main-cont input.ratepay-input-button2:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #runtime{
        margin: 0 0 0 15px;
    }

    #ratepay-Header {
        height: auto;
        margin: 0 0 13px;
        width: 100%;
    }

    #ratepay-Header img {
        float: right;
    }

    #ratepay-Header span {
        font-size: 16px;
    }

    #ratepay-main-cont p.ratepay-Text {
        width: 400px;
    }

    #ratepay-main-cont p.ratepay-Top-Text {
        margin: 20px 15px 0;
    }

    div#ratepay-ContentSwitch {
        margin: 0px 0 0;
        padding: 5px;
        background-color: #eee;
    }

    .ratepay-ContentSwitchDiv {
        width: 190px;
        padding: 2px 0 0 15px;
        color: #263551;
        display: none;
    }

    #ratepay-main-cont #ratepay-DueDate{
    }

    #ratepay-main-cont #debitSelect{
        float: right;
        font-size: 100%;
        margin: 0 3px 0 0;
        text-align: left;
        width: 167px;
        height:60px;
    }
    #ratepay-main-cont .ratepay-DueText{
        float: left;
        margin-top: 10px;
        width: auto;
    }

    #ratepay-ContentSwitch div.ratepay-Active {
        color: #B69767;
    }

    #ratepay-ContentSwitchInput {
        display: block;
        margin-top: 5px;
    }

    #ratepay-SwitchToTerm {
        float: left;
    }

    #ratepay-SwitchToRuntime {
        float: right;
        left: 40px;
        position: relative;
    }

    #ratepay-main-cont .ratepay-Content p {
        margin-bottom: 25px;
    }

    #ratepay-main-cont div.ratepay-Content {

    }

    #ratepay-ContentTerm {
        display:none;
    }

    #ratepay-ContentRuntime {
        display:none;
    }

    #ratepay-main-cont .ratepay-Content select, #ratepay-main-cont .ratepay-Content input.ratepay-Input-amount {
        border: 1px solid #D1DFE0;
        text-align: right;
        position: relative;
        top: 2px;
    }

    #ratepay-main-cont .ratepay-Content select {
        padding: 4px;
        text-align: left;
        width: 110px;
    }

    #ratepay-main-cont .ratepay-Content input.ratepay-Input-amount {
        padding: 4px;
        width: 65px;
    }

    #ratepay-main-cont .ratepay-Content span.ratepay-Currency {
        padding-top: 3px;
        vertical-align: middle;
    }

    /* RatePAY Calculator Result */
   /* RatePAY Calculator Result */
   .rp-table-striped {
       width: 100%;
   }
   * {
       box-sizing: border-box;
   }
   .text-uppercase {
       text-transform: uppercase;
   }
   .text-center {
       padding: 10px 0px;
       border-top: 1px solid #ddd;
       text-align: center;
   }
   .warning {
       background-color: #fcf8e3;
       border-top: 1px solid #ddd;
       border-bottom: 1px solid #ddd;
       padding: 7px 0px;
   }
   .rp-menue, .rp-installment-plan-details, .rp-installment-plan-no-details {
       border-bottom: 1px solid #ddd;
       width: 100%;
       margin: 0px 3px;
       padding: 13px 6px;
   }
   #rp-installment-plan-details {
       display: none;
   }
   #rp-installment-plan-no-details {
       display: block;
   }
   .rp-installment-plan-details:nth-child(odd) {
       background-color: #f9f9f9;
   }
   .rp-installment-plan-title {
       float: left;
   }
   .text-right {
       text-align: right;
   }
   .rp-installment-plan-description {
       display: none;
       position: absolute;
       margin-top: -5px;
   }
   .small {
       font-size: 85%;
   }
    
</style>
<?php $_code = $this->getMethodCode() ?>

<p>Ratepay</p>


<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?></td>
        <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>
<div class="ratepay-Left">
    <?php echo $this->getResultHtml(); ?>
    <?php echo $this->getChildHtml();?>
</div>
<div class="pi-rp-clear"></div>
