<?php
if(is_null(Mage::getSingleton('ratepaypayment/session')->getDeviceIdentToken()) && Mage::helper('checkout/cart')->getItemsCount() > 0) {
    $storeId = Mage::app()->getStore()->getStoreId();
    if (Mage::getStoreConfig("payment/ratepay_general/device_ident", $storeId) == "1") {
        $dfpActive = true;
    } else {
        return;
    }

    $dfpSnippetId = Mage::getStoreConfig("payment/ratepay_general/snipped_id", $storeId);

    if (!empty($dfpSnippetId)) {
        $dfp = Mage::getSingleton('ratepaypayment/libraryconnectorfrontend')->deviceFingerprint(
            $dfpSnippetId,
            Mage::getSingleton('customer/session')->getId()
        );

        Mage::getSingleton('ratepaypayment/session')->setDeviceIdentToken($dfp['token']);

        echo $dfp['dfpSnippetCode'];
    }
}
?>
