<?php
/**
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// @ToDo: Move to helper
if (is_null(Mage::getSingleton('ratepaypayment/session')->getDeviceIdentToken()) && Mage::helper('checkout/cart')->getItemsCount() > 0) {
    $storeId = Mage::app()->getStore()->getStoreId();
    $dfpSnippetId = Mage::getStoreConfig("payment/ratepay_general/snippet_id", $storeId);
    if (empty($dfpSnippetId)) {
        $dfpSnippetId = "ratepay";
    }

    $dfp = Mage::getSingleton('ratepaypayment/libraryConnectorFrontend')->deviceFingerprint(
        $dfpSnippetId,
        Mage::getSingleton('core/session')->getEncryptedSessionId()
    );

    Mage::getSingleton('ratepaypayment/session')->setDeviceIdentToken($dfp['token']);

    echo $dfp['dfpSnippetCode'];
}
?>
