<?php
if(!Mage::getSingleton('ratepaypayment/session')->getDeviceIdentToken() && Mage::helper('checkout/cart')->getItemsCount() > 0) {
    $deviceIdentActive = false;
    $storeId = Mage::app()->getStore()->getStoreId();
    if (Mage::getStoreConfig("payment/ratepay_general/device_ident", $storeId) == "1") {
        $deviceIdentActive = true;
        $deviceIdentId = Mage::getStoreConfig("payment/ratepay_general/snipped_id", $storeId);
    }
    if ($deviceIdentActive && $deviceIdentId) {
        $timestamp = microtime();
        $customerId = Mage::getSingleton('customer/session')->getId();
        $token = md5($customerId . "_" . $timestamp);
        Mage::getSingleton('ratepaypayment/session')->setDeviceIdentToken($token);
        ?>
        <script language="JavaScript">
            var di = {t: '<?php echo $token ?>', v: '<?php echo $deviceIdentId ?>', l: 'Checkout'};
        </script>
        <script type="text/javascript" src="//d.ratepay.com/<?php echo $deviceIdentId ?>/di.js"></script>
        <noscript>
            <link rel="stylesheet" type="text/css" href="//d.ratepay.com/di.css?t=<?php echo $token ?>&v=<?php echo $deviceIdentId ?>&l=Checkout">
        </noscript>
        <?php
    }
}
?>