<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category PayIntelligent
 * @package PayIntelligent_RatePAY
 * @copyright Copyright (c) 2011 PayIntelligent GmbH (http://www.payintelligent.de)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php $_code = $this->getMethodCode() ?>
<?php $bankData = $this->getBankData(); ?>
<style>
    .sp-methods select.ratepayday {width:154px ; margin-right: 7px;}
    .sp-methods select.ratepaymonth {width: 154px ; margin-right: 7px;}
    .sp-methods select.ratepayyear {width: 154px ;}
    .sp-methods input.ratepayphone {width: 147px;}
    .sp-methods div.ratepaybirthdate {width: 476px;}
    .sp-methods .form-list .ratepayagreement {width: auto;float: none;}
</style>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if (!$this->isWhitelabel()): ?>
        <li>
            <button id="<?php echo $_code ?>readmore" type="button" class="button" onclick="document.getElementById('<?php echo $_code ?>description').toggle(); document.getElementById('<?php echo $_code ?>readless').toggle();this.toggle();"><span><span><?php echo $this->__('Pi Read more') ?></span></span></button>
            <div id='<?php echo $_code ?>description' style="display:none;">
                <span style="color: #000000; font-weight: bold;"><?php echo $this->getPaymentHelper()->getStoreName(); ?></span>
                <?php echo $this->__('Pi ratepay_directdebit_info_block_1') ?>
                <a href="http://www.ratepay.com" target="_block" style="font-weight: bold; color: #000000">RatePAY</a>
                <?php echo sprintf($this->__('Pi ratepay_directdebit_info_block_2'), $this->getDueDays()) ?>
            </div>
            <br />
            <button style="display:none;" id="<?php echo $_code ?>readless" type="button" class="button" onclick="document.getElementById('<?php echo $_code ?>description').toggle(); document.getElementById('<?php echo $_code ?>readmore').toggle();this.toggle();"><span><span><?php echo $this->__('Pi Read less') ?></span></span></button>
        </li>
        <br/>
    <?php endif; ?>

    <ul style="border: 1px solid #BDBDBD; padding-left: 4px;">
        <li><label><?php echo $this->__('Pi Ratepay address') ?></label></li>
        <li><label><?php echo $this->__('Pi Creditor') ?>: <?php echo $this->__('Pi RatePAY Creditor ID') ?></label></li>
        <li><label><?php echo $this->__('Pi Mandate') ?>: <?php echo $this->__('Pi Mandate Ref') ?></label></li>
    </ul>
    <br/>
    <ul>
        <li>
            <label>
                <?php echo $this->__('Pi insert bank data'); ?>
            </label>
        </li>
        <li>
            <label for="<?php echo $_code ?>_account_holder" class="required"><em>*</em><?php echo $this->__('Pi Account holder'); ?></label>
            <div class="input-box">
                <input value="<?php echo $bankData['owner'] ?>" type="text" name="payment[<?php echo $_code ?>_account_holder]" id="<?php echo $_code ?>_account_holder" class="input-text required-entry"/>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_account_number" class="required"><em>*</em><?php echo $this->__('Pi IBAN') . " / " . $this->__('Pi Account number'); ?></label>
            <div class="input-box">
                <input value="<?php echo (!empty($bankData['iban'])) ? $bankData['iban'] : $bankData['accountnumber'] ?>" type="text" name="payment[<?php echo $_code ?>_account_number]" id="<?php echo $_code ?>_account_number" class="input-text required-entry" onkeyup="switchAccountType(this)" onchange="switchAccountType(this)" />
            </div>
        </li>
        <li id="li_<?php echo $_code ?>_bank_code_number" style="display: <?php echo (!empty($bankData['iban'])) ? "none" : "inline-block" ?>;">
            <label for="<?php echo $_code ?>_bank_code_number" class="required"><em>*</em><?php echo $this->__('Pi SWIFT-BIC'); ?> / <?php echo $this->__('Pi Bank code number'); ?></label>
            <div class="input-box">
                <input value="<?php echo $bankData['bankcode'] ?>" type="text" name="payment[<?php echo $_code ?>_bank_code_number]" id="<?php echo $_code ?>_bank_code_number" class="input-text"/>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_bank_name" class="required"><em>*</em><?php echo $this->__('Pi Bank name'); ?></label>
            <div class="input-box">
                <input value="<?php echo $bankData['bankname'] ?>" type="text" name="payment[<?php echo $_code ?>_bank_name]" id="<?php echo $_code ?>_bank_name" class="input-text required-entry"/>
            </div>
        </li>
    </ul>
    <?php if ($this->isAdditionalFieldsNeeded()): ?>
        <li>
            <b><?php echo $this->__('Pi Missing contact informations'); ?></b>
        </li>
    <?php endif; ?>

    <?php if ($this->isTaxvatNeeded()): ?>
        <li>
            <label for="<?php echo $_code ?>_taxvat" class="required"><em>*</em><?php echo $this->__('Pi Tax/VAT number'); ?></label>
            <div class="input-box">
                <input value="" type="text" name="payment[<?php echo $_code ?>_taxvat]" id="<?php echo $_code ?>_taxvat" name="payment[<?php echo $_code ?>_taxvat]" class="input-text required-entry"/>
            </div>
        </li>
    <?php endif; ?>

    <?php if (!$this->isPhoneSet()): ?>
        <li>
            <label for="<?php echo $_code ?>_phone" class="required"><em>*</em><?php echo $this->__('Pi Phone'); ?></label>
            <div class="input-box">
                <input value="" type="text" name="payment[<?php echo $_code ?>_phone]" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code ?>_phone]" class="input-text required-entry ratepayphone"/>
            </div>
        </li>
    <?php endif; ?>
    <?php if (!$this->isDobSet()): ?>
        <li><label for="month" class="required"><em>*</em><?php echo $this->__('Pi Date of Birth') ?></label>
            <div class="input-box customer-dob ratepaydirectdebitdob" id="ratepay_directdebit_dob">
                <div class="dob-day">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Pi Day') ?>" value="" name="payment[<?php echo $_code ?>_day]" id="<?php echo $_code ?>_day">
                    <label for="<?php echo $_code ?>_day">DD</label>
                </div><div class="dob-month">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Pi Month') ?>" value="" name="payment[<?php echo $_code ?>_month]" id="<?php echo $_code ?>_month">
                    <label for="<?php echo $_code ?>_month">MM</label>
                </div><div class="dob-year">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Pi Year') ?>" value="" name="payment[<?php echo $_code ?>_year]" id="<?php echo $_code ?>_year" autocomplete="off">
                    <label for="<?php echo $_code ?>_year">YYYY</label>
                </div>    <div style="display:none;" class="dob-full">
                    <input type="hidden" name="<?php echo $_code ?>_dob" id="<?php echo $_code ?>_dob">
                </div>

                <div style="display:none;" class="validation-advice"></div>
            </div>
            <script type="text/javascript">
                //&lt;![CDATA[
                var customer_dob = new Varien.RatepayDOB('.ratepaydirectdebitdob', true, '%d.%m.%y');
                //]]&gt;
            </script>
        </li>
    <?php endif; ?>
        <li>
            <table>
                <tr>
                    <td>
                        <input type="checkbox" class="checkbox" value="1" name="payment[<?php echo $_code ?>_agreement]" id="<?php echo $_code ?>_agreement" >
                    </td>
                    <td>
                        <span class="required ratepayagreement">
                            <?php echo $this->__('Pi ratepay_directdebit_sepa_terms_block_1');?>
                            <?php echo $this->__('Pi Ratepay address');?>
                            <?php echo $this->__('Pi ratepay_directdebit_sepa_terms_block_2');?>
                            <a target="_blank" href="<?php echo Mage::getStoreConfig("payment/ratepay_directdebit/privacy_policy",$this->getQuote()->getStoreId()); ?>"><?php echo $this->__('Pi RatePAY Data Privacy Policy');?></a>
                            <?php echo $this->__('Pi ratepay_directdebit_sepa_terms_block_3');?>
                        </span>
                    </td>
                </tr><tr>
                    <td></td>
                    <td>
                        <br/>
                        <span style="font-weight:bold;"><?php echo $this->__('Pi ratepay_directdebit_sepa_notice_block_1');?></span>
                        <br/>
                        <?php echo $this->__('Pi ratepay_directdebit_sepa_notice_block_2');?>
                        <br/>
                        <?php echo $this->__('Pi ratepay_directdebit_sepa_notice_block_3');?>
                    </td>
                </tr>
            </table>
        </li>
</ul>