<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
$_code = $this->getMethodCode();
$dob = $this->getDob();
?>
<style>

    .sp-methods select.ratepayday {
        width:154px ; margin-right: 7px;
    }

    .sp-methods select.ratepaymonth {
        width: 154px ; margin-right: 7px;
    }

    .sp-methods select.ratepayyear {
        width: 154px ;
    }

    .sp-methods input.ratepayphone {
        width: 147px;
    }

    .sp-methods div.ratepaybirthdate {
        width: 476px;
    }
    #piprmain-cont h1,#piprmain-cont h2,#piprmain-cont td,#piprmain-cont th{
        color: black!important;
    }
    /* reset */
    #pirpmain-cont, #pirpmain-cont div, #pirpmain-cont span, #pirpmain-cont p, #pirpmain-cont input, #pirpmain-cont select, #pirpmain-cont h2, #pirpmain-cont table, #pirpmain-cont td {
        font: 13px  Tahoma;
        line-height: 17px;
        text-align: left;
    }

    /* RatePAY Calculator */
    .piRpClearFix {
        clear: both;
        line-height: 1px;
        height: 1px;
    }

    #pirpmain-cont {
        color: black!important;
        width: 472px !important;
        margin: 0 auto;
        vertical-align: middle;
    }

    #pirpmain-cont input.piRpInput-button {
        width:173px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 8px;
        right:5px;
        margin-left: 15px;
    }
    #pirpmain-cont input.piRpInput-button2 {
        width:173px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 4px;
        right:5px;
    }
    #pirpmain-cont input.piRpInput-button:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #pirpmain-cont input.piRpInput-button2:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #runtime{
        margin: 0 0 0 15px;
    }

    #piRpHeader {
        height: auto;
        width: 100%;
    }

    #piRpHeader img {
        float: right;
        margin-bottom: 3px;
    }

    #piRpHeader span {
        font-size: 16px;
    }

    #pirpmain-cont p.piRpText {
        width: 400px;
    }

    #pirpmain-cont p.piRpTop-Text {
        margin: 20px 15px 0;
    }

    div#piRpContentSwitch {
        margin: 0px 0 0;
        padding: 5px;
        background-color: #eee;
    }

    .piRpContentSwitchDiv {
        width: 190px;
        padding: 2px 0 0 15px;
        color: #263551;
        display: none;
    }

    #pirpmain-cont #piRpDueDate{
    }

    #pirpmain-cont #debitSelect{
        float: right;
        font-size: 100%;
        margin: 0 3px 0 0;
        text-align: left;
        width: 167px;
        height:60px;
    }
    #pirpmain-cont .piRpDueText{
        float: left;
        margin-top: 10px;
        width: auto;
    }

    #piRpContentSwitch div.piRpActive {
        color: #B69767;
    }

    #piRpContentSwitchInput {
        display: block;
        margin-top: 5px;
    }

    #piRpSwitchToTerm {
        float: left;
    }

    #piRpSwitchToRuntime {
        float: right;
        left: 40px;
        position: relative;
    }

    #pirpmain-cont .piRpContent p {
        margin-bottom: 25px;
    }

    #pirpmain-cont div.piRpContent {

    }

    #piRpContentTerm {
        display:none;
    }

    #piRpContentRuntime {
        display:none;
    }

    #pirpmain-cont .piRpContent select, #pirpmain-cont .piRpContent input.piRpInput-amount {
        border: 1px solid #D1DFE0;
        text-align: right;
        position: relative;
        top: 2px;
    }

    #pirpmain-cont .piRpContent select {
        padding: 2px;
        text-align: left;
        width: 95px;
    }

    #pirpmain-cont .piRpContent input.piRpInput-amount {
        padding: 2px;
        width: 50px;
    }

    #pirpmain-cont .piRpContent span.piRpCurrency {
        padding-top: 3px;
        vertical-align: middle;
    }

    /* RatePAY Calculator Result */
    #pirpmain-cont #piRpResult {
        background: none repeat scroll 0 0 #fefefe;
        color: black;
        margin-top: 10px;
    }
    /* RatePAY Calculator Result */
    #pirpmain-cont #piRpResult2 {
        background: none repeat scroll 0 0 #fefefe;
        color: black;
        margin-top: 10px;
    }

    #pirpmain-cont #piRpNotfication {
        background: none repeat scroll 0 0 #FFFFE0;
        border: 1px solid #E6DB55;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px 5px 5px 5px;
        color: #263551;
        margin: 10px 0 11px 0px;
        padding: 10px 5px;
    }

    #pirpmain-cont .pirperror {
        background: none repeat scroll 0 0 #FFEBE8;
        border: 1px solid #CC0000;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px 5px 5px 5px;
        color: #263551;
        padding: 10px;
        margin: 10px 0 11px 0px;
    }

    #pirpmain-cont h2.pirpmid-heading {
        color: black;
        font-size: 12px;
        margin: 5px 0;
        padding-left: 5px;
    }

    #piRpResult table{
        border: none;
    }
    #piRpResult2 table{
        border: none;
    }
    #piInstallmentTerms table,#piInstallmentTerms td,#piInstallmentTerms th {
        border: none;
        padding: 0px;
    }
    #piInstallmentTerms th {
        padding-left:10px;
        text-align: left;
        width: 240px;
        border: none;
        vertical-align: middle;
    }

    #piInstallmentTerms td {
        text-align: right;
        color: black;
        border: none;
        vertical-align: middle;
    }

    #piInstallmentTerms label {
        border: 1px solid #DDDDDD;
        display: inline-block;
        margin-top: 4px;
        padding-bottom: 5px;
    }

    #piInstallmentTerms tr.piHighlight th {
        padding-left: 0;
        color: black;
        border: none;
    }

    #piInstallmentTerms tr.piHighlight th, #piInstallmentTerms tr.piHighlight td {
        color: black;
        border: none;
    }

    #piInstallmentTerms th, #piInstallmentTerms td {
        color: black;
        border: none;
    }

    #piInstallmentTerms tr.piTableHr th, #piInstallmentTerms tr.piTableHr td {
        color: black;
        border: none;
    }

    #piInstallmentTerms tr.piTableHr {
        color: black;
        border: none;
    }

    #piInstallmentTerms tr.piPriceSectionHead td, #piInstallmentTerms tr.piPriceSectionHead th {
        color: black;
        border: none;
    }

    table#piInstallmentTerms {
        color: black;
        margin: 0 auto;
        padding: 5px 3px;
        width: 415px !important;
    }

    #pirpmain-cont .piRpH2{
        color: black;
        float: left;
        font-size: 18px;
        font-weight: bold;
        margin: 20px 0 0 10px;
    }

    #pirpmain-cont .piRpLogoText{
        float: right;
        font-size: 10px;
        padding-right: 5px;
        margin-top: -3px;
    }
    .piRpFullWidth{
        width: 100%;
        height: 20px;
    }

    #pirpmain-cont .piRpChooseRuntime{
        border: 1px solid;
        font-size: 95%;
        padding: 10px;
    }
    .piRpFloatLeft{
        float: left;
    }

    .piRpNintyPercentWidth{
        padding-top: 13px;
        width: 90%;
    }

    #pirpmain-cont .piRpChooseInput{
        background: url("<?php echo $this->getSkinUrl('images/ratepay/arrow.png'); ?>") no-repeat scroll 0 0 transparent;
        float: left;
        height: 40px;
        padding-left: 13px;
    }


    #pirpmain-cont .piRpChooseInput Input{
        margin-top: 13px;
    }

    #debitSelect{
        padding: 2px;
        width:123px;
        margin: 0px;
    }
    .piRpMouseoverInfo{
        background-color: #263552;
        color: white;
        border: 1px solid black;
        bottom: 0;
        display: none;
        float: left;
        font-size: 8px;
        height: auto;
        left: 20px;
        position: absolute;
        max-width: 350px;
        padding: 5px;
    }
    .piRpInfoImg{
        width: 12px;
        height: 12px;
    }
    .piRpInfoImgDiv{
        float: left;
        height: 16px;
        padding: 2px 3px;
        width: 16px;
    }

    #pirpmain-cont .piRpCalculationText{
        font-size: 85%;
        padding-top: 15px;
    }
    .piRpRelativePosition{
        position: relative;
    }


    .piRpyellow{
        background-color: #F2C551;
    }

    #piInstallmentTerms td.piRpPercentWidth{
        width: 250px;
    }
    .piRpMarginTop{
        margin-top: 10px;

    }

    #piInstallmentTerms .piRpPaddingBottom{
        padding-bottom: 10px;
    }
    #piInstallmentTerms .piRpPaddingRight{
        padding-right: 10px;
    }

    #piInstallmentTerms .piRpPaddingLeft{
        padding-left: 10px;
    }

    #piInstallmentTerms .piRpPaddingTop{
        padding-top: 10px;
    }

    #piRpContentRuntime option{
        border-right: 1px solid #ccc;
        padding-left: 8px;
        padding-top: 2px;
        font-size: 100%;
        text-align: left;
    }

    #pirpmain-cont .piRpVertAlignMiddle{
        vertical-align: middle;
    }

    #piInstallmentTerms .piRpPercentWith{
        float: left;
        text-align: right;
        width: 50px;
    }
    #piInstallmentTerms .piRpTextAlignLeft{
        text-align: left;
    }
    #piInstallmentTerms #piInstallmentThirdTd{
        width: 10px;
    }

    #pirpmain-cont .piRpContent .piRpDueDateSelect{
        float: right;
        width: 167px;
        height:60px;
    }
    #pirpmain-cont .piRpContent .piRpDueDateSelect option{
        border-right: 0px solid;
    }

    #pirpmain-cont input.ajaxloader{
        background: url("<?php echo $this->getSkinUrl('images/ratepay/ajaxloader.gif'); ?>")no-repeat 140px 1px #f2B551;
    }

    #debitSelectRuntime option {
        padding: 0px;
    }

    .piRpMarginBottom {
        margin-bottom: 5px;
    }
</style>
<?php $monthAllowed = $this->getMonthAllowed() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if (!$this->isWhitelabel()): ?>
        <li>
            <button id="<?php echo $_code ?>readmore" type="button" class="button" onclick="document.getElementById('<?php echo $_code ?>description').toggle(); document.getElementById('<?php echo $_code ?>readless').toggle();this.toggle();"><span><span><?php echo $this->__('Read more') ?></span></span></button>
            <div id='<?php echo $_code ?>description' style="display:none;">
                <div style="font-weight:bold;">
                    <?php echo $this->__('ratepay_rate_info_block_1') ?><br/>
                </div>
                <br/>
                <div>
                    <?php echo $this->__('ratepay_rate_info_block_2'); ?>
                    <span style="font-weight:bold;"><?php echo min($monthAllowed['month_allowed']) ?></span>
                    <?php echo $this->__('up to') ?>
                    <span style="font-weight:bold;"><?php echo max($monthAllowed['month_allowed']) ?></span>
                    <?php echo $this->__('ratepay_rate_info_block_3') ?>
                    <span style="font-weight:bold;"><?php echo $monthAllowed['rate_min'] ?> &euro;</span>
                    <?php echo $this->__('ratepay_rate_info_block_4') ?>
                </div>
            </div>
            <br />
            <button style="display:none;" id="<?php echo $_code ?>readless" type="button" class="button" onclick="document.getElementById('<?php echo $_code ?>description').toggle(); document.getElementById('<?php echo $_code ?>readmore').toggle();this.toggle();"><span><span><?php echo $this->__('Read less') ?></span></span></button>
        </li>
    <?php endif; ?>

    <?php if ($this->isAdditionalFieldsNeeded()): ?>
        <li>
            <b><?php echo $this->__('Missing contact informations'); ?></b>
        </li>
    <?php endif; ?>

    <?php if ($this->isB2b()): ?>
        <li id="vatIdForm_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "inline-block" : "none"; ?>">
            <label for="<?php echo $_code ?>_taxvat" class="required"><em>*</em><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getVatId() ?>" type="text" name="payment[<?php echo $_code ?>_taxvat]" id="<?php echo $_code ?>_taxvat" name="payment[<?php echo $_code ?>_taxvat]" class="input-text required-entry"/>
            </div>
        </li>
        <li id="vatIdLabel_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "none" : "inline-block"; ?>">
            <label><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="dob-day">
                <label><?php echo $this->getVatId() ?>&nbsp;<a onclick="alterVatId('rate')"><?php echo $this->__('Alter') ?></a></label>
            </div>
        </li>
        <br/>
    <?php endif; ?>

    <?php if (!$this->isValidPhone()): ?>
        <li>
            <label for="<?php echo $_code ?>_phone" class="required"><em>*</em><?php echo $this->__('Phone'); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getPhone() ?>" type="text" name="payment[<?php echo $_code ?>_phone]" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code ?>_phone]" class="input-text required-entry ratepayphone"/>
            </div>
        </li>
    <?php endif; ?>

    <li id="dobForm_rate" style="display: <?php echo ($this->isDobSet()) ? "none" : "inline-block"; ?>">
        <label for="month" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
        <div class="input-box customer-dob ratepayratedob" id="">
            <div class="dob-day">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Day') ?>" value="<?php if ($dob) echo substr($dob, 8, 2) ?>" name="payment[<?php echo $_code ?>_day]" id="<?php echo $_code ?>_day">
                <label for="<?php echo $_code ?>_day">DD</label>
            </div>
            <div class="dob-month">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Month') ?>" value="<?php if ($dob) echo substr($dob, 5, 2) ?>" name="payment[<?php echo $_code ?>_month]" id="<?php echo $_code ?>_month">
                <label for="<?php echo $_code ?>_month">MM</label>
            </div>
            <div class="dob-year">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Year') ?>" value="<?php if ($dob) echo substr($dob, 0, 4) ?>" name="payment[<?php echo $_code ?>_year]" id="<?php echo $_code ?>_year">
                <label for="<?php echo $_code ?>_year">YYYY</label>
            </div>
            <div style="display:none;" class="dob-full">
                <input type="hidden" name="<?php echo $_code ?>_dob" id="<?php echo $_code ?>_dob">
            </div>

            <div style="display:none;" class="validation-advice"></div>
        </div>
        <script type="text/javascript">
            //&lt;![CDATA[
            var customer_dob = new Varien.RatepayDOB('.ratepayratedob', true, '%d.%m.%y');
            //]]&gt;
        </script>
    </li>
    <li id="dobLabel_rate" style="display: <?php echo ($this->isDobSet()) ? "inline-block" : "none"; ?>">
        <label><?php echo $this->__('Date of Birth') ?></label>
        <div class="dob-day">
            <label><?php echo substr($dob, 8, 2) . "." . substr($dob, 5, 2) . "." . substr($dob, 0, 4) ?> <a onclick="alterDob('rate')"><?php echo $this->__('Alter') ?></a></label>
        </div>
    </li>

    <li>
        <div id="pirpmain-cont">
            <div id="piRpHeader">
                <div class="piRpFullWidth">
                    <h2 class="piRpH2"><?php echo $this->__('Calculate here your own rate'); ?></h2>
                    <?php if (!$this->isWhitelabel()): ?>
                        <img class="piRpLogoImg" src="<?php echo $this->getSkinUrl('images/ratepay/Logo_Ratepay_Ratenrechner_01_Final_RGB_Farbe_01-small_.png'); ?>" width="141" height="43" alt="RatePAY Logo">
                    <?php endif; ?>
                </div>
                <br class="piRpClearFix" />
            </div>

            <div id="piRpContentSwitch">
                <div class="piRpChooseRuntime">
                    <?php echo $this->__('lang_cash_payment_price_part_one'); ?>:
                    <span><b><?php echo Mage::helper('checkout')->formatPrice($this->getAmount(), true, true); ?></b></span>
                    <?php echo $this->__('lang_cash_payment_price_part_two'); ?>
                    <br />
                    <label for="firstInput" style="width:100%;">
                        <div class="piRpChooseInput" id="piRpChooseInputRate">
                            <input id="firstInput" class="piRpFloatLeft" type="radio" name="Zahlmethode" value="wishrate"  onClick="switchRateOrRuntime('rate', '<?php echo $this->getSkinUrl(); ?>');" checked="checked">
                        </div>
                        <div class="piRpNintyPercentWidth piRpFloatLeft" style="color: black; width: 390px;"><?php echo $this->__('lang_payment_text_wishrate'); ?></div>
                    </label>
                    <div id="piRpContentTerm" class="piRpContent" style="display: none;">
                        <!--<?php if ($this->isDynamicDue()) { ?>
                            <div id="piRpDueDate" class="piRpDueDate">
                                <div class="piRpDueText"><?php echo $this->__('lang_due_date'); ?></div>
                                <select name="piRpDueDateSelect" id="debitSelect" size="3">
                                    <option value="1"><?php echo $this->__('At 1st of month'); ?></option>
                                    <option value="15"><?php echo $this->__('At 15th of month'); ?></option>
                                    <option value="28" selected="selected"><?php echo $this->__('At 28th of month'); ?></option>
                                </select>
                            </div>
                        <?php } ?>-->
                        <br class="piRpClearFix" />
                        <div class="piRpMarginTop">
                            <span class="piRpVertAlignMiddle"><?php echo $this->__('lang_please') . " " . $this->__('lang_insert_wishrate'); ?>:</span>
                            <input name="" id="rate" class="piRpInput-amount" type="text">
                            <span class="piRpCurrency"> &euro;</span>
                            <input name="" onclick="piRatepayRateCalculatorAction('rate', '<?php echo $this->getUrl("ratepaypayment/ratenrechner/rate", array('_secure' => true)); ?>');" value="<?php echo $this->__('lang_calculate_runtime'); ?>" id="piRpInput-button" class="piRpInput-button" type="button">
                        </div>
                    </div>
                    <br class="piRpClearFix" />
                    <label for="secondInput" style="width:100%;">
                        <div class="piRpChooseInput" id="piRpChooseInputRuntime">
                            <input id="secondInput" class="piRpFloatLeft" type="radio" name="Zahlmethode" value="runtime" onClick="switchRateOrRuntime('runtime', '<?php echo $this->getSkinUrl(); ?>');">
                        </div>
                        <div class="piRpNintyPercentWidth piRpFloatLeft" style="color: black;"><?php echo $this->__('lang_payment_text_runtime'); ?></div>
                    </label>
                    <div id="piRpContentRuntime" class="piRpContent" style="display: none;">
                        <!--<?php if ($this->isDynamicDue()) { ?>
                            <div id="piRpDueDate" class="piRpDueDate">
                                <div class="piRpDueText"><?php echo $this->__('lang_due_date'); ?></div>
                                <span style="float: right;">
                                    <select name="piRpDueDateSelect" id="debitSelectRuntime" size="3" style="width: 167px;">
                                        <option value="1"><?php echo $this->__('At 1st of month'); ?></option>
                                        <option value="15"><?php echo $this->__('At 15th of month'); ?></option>
                                        <option value="28" selected="selected"><?php echo $this->__('At 28th of month'); ?></option>
                                    </select>
                                </span>
                            </div>
                        <?php } ?>-->
                        <br class="piRpClearFix" />
                        <div class="piRpMarginTop">
                            <span class="piRpVertAlignMiddle" style="float: left;"><?php echo $this->__('lang_please') . " " . $this->__('lang_insert_runtime'); ?>:</span>
                            <select id="runtime">
                                <?php
                                foreach ($monthAllowed['month_allowed'] as $month) {
                                    echo '<option value="' . $month . '">';
                                    if ($month < 10)
                                        echo'&nbsp;'; echo $month . ' ' . $this->__('lang_months') . '</option>';
                                }
                                ?>
                            </select>
                            <input name="" onclick="piRatepayRateCalculatorAction('runtime', '<?php echo $this->getUrl("ratepaypayment/ratenrechner/runtime", array('_secure' => true)); ?>');" value="<?php echo $this->__('lang_calculate_rate'); ?>" value="<?php echo $this->__('lang_calculate_rate'); ?>" type="button" id="piRpInput-buttonRuntime"  class="piRpInput-button2">
                        </div>
                    </div>
                    <br class="piRpClearFix" />
                    <div class="piRpContentSwitchDiv" id="piRpSwitchToTerm" class="piRpActive" style="display: none">
                        <span id="pirpspanrate">
                            <?php echo $this->__('lang_insert_wishrate'); ?> <?php echo $this->__('lang_calculate_runtime'); ?>
                        </span>
                        <input name="" value="<?php echo $this->__('lang_calculate_runtime'); ?>" type="button" class="piRpInput-button piRpContentSwitchInput ">
                    </div>
                    <div class="piRpContentSwitchDiv"  id="piRpSwitchToRuntime" style="display: none">
                        <span id="pirpspanruntime" class="pirpactive">
                            <?php echo $this->__('lang_choose_runtime'); ?> <?php echo $this->__('lang_calculate_rate'); ?>
                        </span>
                        <input name="" value="<?php echo $this->__('lang_calculate_rate'); ?>" type="button" class="piRpInput-button piRpContentSwitchInput ">
                    </div>
                    <div id="piRpResultContainer"></div>
                </div>
            </div>
            <script>
                switchRateOrRuntime('rate', '<?php echo $this->getSkinUrl(); ?>');
            </script>

            <br class="piRpClearFix" />
        </div>
    </li>
</ul>
