<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
$_code = $this->getMethodCode();
$dob = $this->getDob();
$monthAllowed = $this->getMonthAllowed();

echo $this->getDeviceIdentToken();
?>

<style>

    .sp-methods select.ratepayday {
        width:154px ; margin-right: 7px;
    }

    .sp-methods select.ratepaymonth {
        width: 154px ; margin-right: 7px;
    }

    .sp-methods select.ratepayyear {
        width: 154px ;
    }

    .sp-methods input.ratepayphone {
        width: 147px;
    }

    .sp-methods div.ratepaybirthdate {
        width: 476px;
    }
    #ratepay-main-cont h1,#ratepay-main-cont h2,#ratepay-main-cont td,#ratepay-main-cont th{
        color: black!important;
    }
    /* reset */
    #ratepay-main-cont, #ratepay-main-cont div, #ratepay-main-cont span, #ratepay-main-cont p, #ratepay-main-cont input, #ratepay-main-cont select, #ratepay-main-cont h2, #ratepay-main-cont table, #ratepay-main-cont td {
        font: 13px  Tahoma;
        line-height: 17px;
        text-align: left;
    }

    /* RatePAY Calculator */
    .ratepay-ClearFix {
        clear: both;
        line-height: 1px;
        height: 1px;
    }

    #ratepay-main-cont {
        color: black!important;
        width: 472px !important;
        margin: 0 auto;
        vertical-align: middle;
    }

    #ratepay-main-cont input.ratepay-Input-button {
        width:173px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 8px;
        right:5px;
        margin-left: 15px;
    }
    #ratepay-main-cont input.ratepay-Input-button2 {
        width:173px;
        color:#000;
        background:#f2c551;
        border:2px solid #f2c551;
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        font-weight:bold;
        cursor:pointer;
        position:relative;
        text-align: center;
        float: right;
        top: 4px;
        right:5px;
    }
    #ratepay-main-cont input.ratepay-Input-button:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #ratepay-main-cont input.ratepay-Input-button2:hover {
        background-color:#f2B551;
        border:2px solid #f2C551;
    }
    #runtime{
        margin: 0 0 0 15px;
    }

    #ratepay-Header {
        height: auto;
        width: 100%;
    }

    #ratepay-Header img {
        float: right;
        margin-bottom: 3px;
    }

    #ratepay-Header span {
        font-size: 16px;
    }

    #ratepay-main-cont p.ratepay-Text {
        width: 400px;
    }

    #ratepay-main-cont p.ratepay-Top-Text {
        margin: 20px 15px 0;
    }

    div#ratepay-ContentSwitch {
        margin: 0px 0 0;
        padding: 5px;
        background-color: #eee;
    }

    .ratepay-ContentSwitchDiv {
        width: 190px;
        padding: 2px 0 0 15px;
        color: #263551;
        display: none;
    }

    #ratepay-main-cont #ratepay-DueDate{
    }

    #ratepay-main-cont #debitSelect{
        float: right;
        font-size: 100%;
        margin: 0 3px 0 0;
        text-align: left;
        width: 167px;
        height:60px;
    }
    #ratepay-main-cont .ratepay-DueText{
        float: left;
        margin-top: 10px;
        width: auto;
    }

    #ratepay-ContentSwitch div.ratepay-Active {
        color: #B69767;
    }

    #ratepay-ContentSwitchInput {
        display: block;
        margin-top: 5px;
    }

    #ratepay-SwitchToTerm {
        float: left;
    }

    #ratepay-SwitchToRuntime {
        float: right;
        left: 40px;
        position: relative;
    }

    #ratepay-main-cont .ratepay-Content p {
        margin-bottom: 25px;
    }

    #ratepay-main-cont div.ratepay-Content {

    }

    #ratepay-ContentTerm {
        display:none;
    }

    #ratepay-ContentRuntime {
        display:none;
    }

    #ratepay-main-cont .ratepay-Content select, #ratepay-main-cont .ratepay-Content input.ratepay-Input-amount {
        border: 1px solid #D1DFE0;
        text-align: right;
        position: relative;
        top: 2px;
    }

    #ratepay-main-cont .ratepay-Content select {
        padding: 2px;
        text-align: left;
        width: 95px;
    }

    #ratepay-main-cont .ratepay-Content input.ratepay-Input-amount {
        padding: 2px;
        width: 50px;
    }

    #ratepay-main-cont .ratepay-Content span.ratepay-Currency {
        padding-top: 3px;
        vertical-align: middle;
    }

    /* RatePAY Calculator Result */
    #ratepay-main-cont #ratepay-Result {
        background: none repeat scroll 0 0 #fefefe;
        color: black;
        margin-top: 10px;
    }
    /* RatePAY Calculator Result */
    #ratepay-main-cont #ratepay-Result2 {
        background: none repeat scroll 0 0 #fefefe;
        color: black;
        margin-top: 10px;
    }

    #ratepay-main-cont #ratepay-Notfication {
        background: none repeat scroll 0 0 #FFFFE0;
        border: 1px solid #E6DB55;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px 5px 5px 5px;
        color: #263551;
        margin: 10px 0 11px 0px;
        padding: 10px 5px;
    }

    #ratepay-main-cont .ratepay-error {
        background: none repeat scroll 0 0 #FFEBE8;
        border: 1px solid #CC0000;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px 5px 5px 5px;
        color: #263551;
        padding: 10px;
        margin: 10px 0 11px 0px;
    }

    #ratepay-main-cont h2.ratepay-mid-heading {
        color: black;
        font-size: 12px;
        margin: 5px 0;
        padding-left: 5px;
    }

    #ratepay-Result table{
        border: none;
    }
    #ratepay-Result2 table{
        border: none;
    }
    #ratepay-InstallmentTerms table,#ratepay-InstallmentTerms td,#ratepay-InstallmentTerms th {
        border: none;
        padding: 0px;
    }
    #ratepay-InstallmentTerms th {
        padding-left:10px;
        text-align: left;
        width: 240px;
        border: none;
        vertical-align: middle;
    }

    #ratepay-InstallmentTerms td {
        text-align: right;
        color: black;
        border: none;
        vertical-align: middle;
    }

    #ratepay-InstallmentTerms label {
        border: 1px solid #DDDDDD;
        display: inline-block;
        margin-top: 4px;
        padding-bottom: 5px;
    }

    #ratepay-InstallmentTerms tr.ratepay-Highlight th {
        padding-left: 0;
        color: black;
        border: none;
    }

    #ratepay-InstallmentTerms tr.ratepay-Highlight th, #ratepay-InstallmentTerms tr.ratepay-Highlight td {
        color: black;
        border: none;
    }

    #ratepay-InstallmentTerms th, #ratepay-InstallmentTerms td {
        color: black;
        border: none;
    }

    #ratepay-InstallmentTerms tr.ratepay-TableHr th, #ratepay-InstallmentTerms tr.ratepay-TableHr td {
        color: black;
        border: none;
    }

    #ratepay-InstallmentTerms tr.ratepay-TableHr {
        color: black;
        border: none;
    }

    #ratepay-InstallmentTerms tr.ratepay-PriceSectionHead td, #ratepay-InstallmentTerms tr.ratepay-PriceSectionHead th {
        color: black;
        border: none;
    }

    table#ratepay-InstallmentTerms {
        color: black;
        margin: 0 auto;
        padding: 5px 3px;
        width: 415px !important;
    }

    #ratepay-main-cont .ratepay-H2{
        color: black;
        float: left;
        font-size: 18px;
        font-weight: bold;
        margin: 20px 0 0 10px;
    }

    #ratepay-main-cont .ratepay-LogoText{
        float: right;
        font-size: 10px;
        padding-right: 5px;
        margin-top: -3px;
    }
    .ratepay-FullWidth{
        width: 100%;
        height: 20px;
    }

    #ratepay-main-cont .ratepay-ChooseRuntime{
        border: 1px solid;
        font-size: 95%;
        padding: 10px;
    }
    .ratepay-FloatLeft{
        float: left;
    }

    .ratepay-NintyPercentWidth{
        padding-top: 13px;
        width: 90%;
    }

    #ratepay-main-cont .ratepay-ChooseInput{
        background: url("<?php echo $this->getSkinUrl('images/ratepay/arrow.png'); ?>") no-repeat scroll 0 0 transparent;
        float: left;
        height: 40px;
        padding-left: 13px;
    }


    #ratepay-main-cont .ratepay-ChooseInput Input{
        margin-top: 13px;
    }

    #debitSelect{
        padding: 2px;
        width:123px;
        margin: 0px;
    }
    .ratepay-MouseoverInfo{
        background-color: #263552;
        color: white;
        border: 1px solid black;
        bottom: 0;
        display: none;
        float: left;
        font-size: 8px;
        height: auto;
        left: 20px;
        position: absolute;
        max-width: 350px;
        padding: 5px;
    }
    .ratepay-InfoImg{
        width: 12px;
        height: 12px;
    }
    .ratepay-InfoImgDiv{
        float: left;
        height: 16px;
        padding: 2px 3px;
        width: 16px;
    }

    #ratepay-main-cont .ratepay-CalculationText{
        font-size: 85%;
        padding-top: 15px;
    }
    .ratepay-RelativePosition{
        position: relative;
    }


    .ratepay-yellow{
        background-color: #F2C551;
    }

    #ratepay-InstallmentTerms td.ratepay-PercentWidth{
        width: 250px;
    }
    .ratepay-MarginTop{
        margin-top: 10px;

    }

    #ratepay-InstallmentTerms .ratepay-PaddingBottom{
        padding-bottom: 10px;
    }
    #ratepay-InstallmentTerms .ratepay-PaddingRight{
        padding-right: 10px;
    }

    #ratepay-InstallmentTerms .ratepay-PaddingLeft{
        padding-left: 10px;
    }

    #ratepay-InstallmentTerms .ratepay-PaddingTop{
        padding-top: 10px;
    }

    #ratepay-ContentRuntime option{
        border-right: 1px solid #ccc;
        padding-left: 8px;
        padding-top: 2px;
        font-size: 100%;
        text-align: left;
    }

    #ratepay-main-cont .ratepay-VertAlignMiddle{
        vertical-align: middle;
    }

    #ratepay-InstallmentTerms .ratepay-PercentWith{
        float: left;
        text-align: right;
        width: 50px;
    }
    #ratepay-InstallmentTerms .ratepay-TextAlignLeft{
        text-align: left;
    }
    #ratepay-InstallmentTerms #ratepay-InstallmentThirdTd{
        width: 10px;
    }

    #ratepay-main-cont .ratepay-Content .ratepay-DueDateSelect{
        float: right;
        width: 167px;
        height:60px;
    }
    #ratepay-main-cont .ratepay-Content .ratepay-DueDateSelect option{
        border-right: 0px solid;
    }

    #ratepay-main-cont input.ajaxloader{
        background: url("<?php echo $this->getSkinUrl('images/ratepay/ajaxloader.gif'); ?>")no-repeat 140px 1px #f2B551;
    }

    #debitSelectRuntime option {
        padding: 0px;
    }

    .ratepay-MarginBottom {
        margin-bottom: 5px;
    }

    .ratepay-sandbox-notification {
        border: 2px dashed #000000;
        background-color: #ffff00;
        font-weight: bold;
        font-color: #000000;
        text-align: center;
    }
</style>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->isSandbox()): ?>
        <li class="ratepay-sandbox-notification">
            <?php echo $this->__('Sandbox Notifcation'); ?>
        </li>
    <?php endif; ?>

    <?php if ($this->isAdditionalFieldsNeeded()): ?>
        <li>
            <b><?php echo $this->__('Missing contact informations'); ?></b>
        </li>
    <?php endif; ?>

    <?php if ($this->isB2b()): ?>
        <li id="vatIdForm_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "inline-block" : "none"; ?>">
            <label for="<?php echo $_code ?>_taxvat" class="required"><em>*</em><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getVatId() ?>" type="text" name="payment[<?php echo $_code ?>_taxvat]" id="<?php echo $_code ?>_taxvat" name="payment[<?php echo $_code ?>_taxvat]" class="input-text required-entry"/>
            </div>
        </li>
        <li id="vatIdLabel_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "none" : "inline-block"; ?>">
            <label><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="dob-day">
                <label><?php echo $this->getVatId() ?>&nbsp;<a onclick="alterVatId('rate')"><?php echo $this->__('Alter') ?></a></label>
            </div>
        </li>
        <br/>
    <?php endif; ?>

    <?php if (!$this->isValidPhone()): ?>
        <li>
            <label for="<?php echo $_code ?>_phone" class="required"><em>*</em><?php echo $this->__('Phone'); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getPhone() ?>" type="text" name="payment[<?php echo $_code ?>_phone]" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code ?>_phone]" class="input-text required-entry ratepayphone"/>
            </div>
        </li>
    <?php endif; ?>

    <li id="dobForm_<?php echo $_code ?>" style="display: <?php echo ($this->isDobSet()) ? "none" : "inline-block"; ?>">
        <label for="month" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
        <div class="input-box customer-dob ratepayratedob" id="">
            <div class="dob-day">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Day') ?>" value="<?php if ($dob) echo substr($dob, 8, 2) ?>" name="payment[<?php echo $_code ?>_day]" id="<?php echo $_code ?>_day">
                <label for="<?php echo $_code ?>_day">DD</label>
            </div>
            <div class="dob-month">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Month') ?>" value="<?php if ($dob) echo substr($dob, 5, 2) ?>" name="payment[<?php echo $_code ?>_month]" id="<?php echo $_code ?>_month">
                <label for="<?php echo $_code ?>_month">MM</label>
            </div>
            <div class="dob-year">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Year') ?>" value="<?php if ($dob) echo substr($dob, 0, 4) ?>" name="payment[<?php echo $_code ?>_year]" id="<?php echo $_code ?>_year">
                <label for="<?php echo $_code ?>_year">YYYY</label>
            </div>
            <div style="display:none;" class="dob-full">
                <input type="hidden" name="<?php echo $_code ?>_dob" id="<?php echo $_code ?>_dob">
            </div>

            <div style="display:none;" class="validation-advice"></div>
        </div>
        <script type="text/javascript">
            //&lt;![CDATA[
            var customer_dob = new Varien.RatepayDOB('.ratepayratedob', true, '%d.%m.%y');
            //]]&gt;
        </script>
    </li>
    <li id="dobLabel_<?php echo $_code ?>" style="display: <?php echo ($this->isDobSet()) ? "inline-block" : "none"; ?>">
        <label><?php echo $this->__('Date of Birth') ?></label>
        <div class="dob-day">
            <label><?php echo substr($dob, 8, 2) . "." . substr($dob, 5, 2) . "." . substr($dob, 0, 4) ?> <a onclick="alterDob('rate')"><?php echo $this->__('Alter') ?></a></label>
        </div>
    </li>

    <?php if (count($monthAllowed['month_allowed']) > 1): ?>
        <li>
            <input type="hidden" id="<?php echo $_code ?>_Notification" value="1">
            <div id="ratepay-main-cont">
                <div id="ratepay-Header">
                    <div class="ratepay-FullWidth">
                        <h2 class="ratepay-H2"><?php echo $this->__('Calculate here your own rate'); ?></h2>
                    </div>
                    <br class="ratepay-ClearFix" />
                </div>

                <div id="ratepay-ContentSwitch">
                    <div class="ratepay-ChooseRuntime">
                        <?php echo $this->__('lang_cash_payment_price_part_one'); ?>:
                        <span><b><?php echo Mage::helper('checkout')->formatPrice($this->getAmount(), true, true); ?></b></span>
                        <?php echo $this->__('lang_cash_payment_price_part_two'); ?>
                        <br />
                        <label for="firstInput" style="width:100%;">
                            <div class="ratepay-ChooseInput" id="<?php echo $_code ?>_ChooseInputRate">
                                <input id="firstInput" class="ratepay-FloatLeft" type="radio" name="Zahlmethode" value="wishrate"  onClick="switchRateOrRuntime('rate', '<?php echo $_code ?>', '<?php echo $this->getSkinUrl('images/ratepay/'); ?>');" checked="checked">
                            </div>
                            <div class="ratepay-NintyPercentWidth ratepay-FloatLeft" style="color: black; width: 390px;"><?php echo $this->__('lang_payment_text_wishrate'); ?></div>
                        </label>
                        <div id="<?php echo $_code ?>_ContentTerm" class="ratepay-Content" style="display: none;">
                            <!--<?php if ($this->isDynamicDue()) { ?>
                                <div id="<?php echo $_code ?>_DueDate" class="ratepay-DueDate">
                                    <div class="ratepay-DueText"><?php echo $this->__('lang_due_date'); ?></div>
                                    <select name="<?php echo $_code ?>RpDueDateSelect" id="debitSelect" size="3">
                                        <option value="1"><?php echo $this->__('At 1st of month'); ?></option>
                                        <option value="15"><?php echo $this->__('At 15th of month'); ?></option>
                                        <option value="28" selected="selected"><?php echo $this->__('At 28th of month'); ?></option>
                                    </select>
                                </div>
                            <?php } ?>-->
                            <br class="ratepay-ClearFix" />
                            <div class="ratepay-MarginTop">
                                <span class="ratepay-VertAlignMiddle"><?php echo $this->__('lang_please') . " " . $this->__('lang_insert_wishrate'); ?>:</span>
                                <input id="<?php echo $_code ?>-rate" class="ratepay-Input-amount" type="text">
                                <span class="ratepay-Currency"> &euro;</span>
                                <input onclick="ratepayRateCalculatorAction('rate', '<?php echo $_code ?>', '<?php echo $this->getUrl("ratepaypayment/ratenrechner/rate", array('_secure' => true)); ?>');" value="<?php echo $this->__('lang_calculate_runtime'); ?>" id="<?php echo $_code ?>_Input-button" class="ratepay-Input-button" type="button">
                            </div>
                        </div>
                        <br class="ratepay-ClearFix" />
                        <label for="secondInput" style="width:100%;">
                            <div class="ratepay-ChooseInput" id="<?php echo $_code ?>_ChooseInputRuntime">
                                <input id="secondInput" class="ratepay-FloatLeft" type="radio" name="Zahlmethode" value="runtime" onClick="switchRateOrRuntime('runtime', '<?php echo $_code ?>', '<?php echo $this->getSkinUrl('images/ratepay/'); ?>');">
                            </div>
                            <div class="ratepay-NintyPercentWidth ratepay-FloatLeft" style="color: black;"><?php echo $this->__('lang_payment_text_runtime'); ?></div>
                        </label>
                        <div id="<?php echo $_code ?>_ContentRuntime" class="ratepay-Content" style="display: none;">
                            <!--<?php if ($this->isDynamicDue()) { ?>
                                <div id="<?php echo $_code ?>_DueDate" class="ratepay-DueDate">
                                    <div class="ratepay-DueText"><?php echo $this->__('lang_due_date'); ?></div>
                                    <span style="float: right;">
                                        <select name="<?php echo $_code ?>RpDueDateSelect" id="debitSelectRuntime" size="3" style="width: 167px;">
                                            <option value="1"><?php echo $this->__('At 1st of month'); ?></option>
                                            <option value="15"><?php echo $this->__('At 15th of month'); ?></option>
                                            <option value="28" selected="selected"><?php echo $this->__('At 28th of month'); ?></option>
                                        </select>
                                    </span>
                                </div>
                            <?php } ?>-->
                            <br class="ratepay-ClearFix" />
                            <div class="ratepay-MarginTop">
                                <span class="ratepay-VertAlignMiddle" style="float: left;"><?php echo $this->__('lang_please') . " " . $this->__('lang_insert_runtime'); ?>:</span>
                                <select id="<?php echo $_code ?>-runtime">
                                    <?php
                                    foreach ($monthAllowed['month_allowed'] as $month) {
                                        echo '<option value="' . $month . '">';
                                        if ($month < 10)
                                            echo'&nbsp;'; echo $month . ' ' . $this->__('lang_months') . '</option>';
                                    }
                                    ?>
                                </select>
                                <input name="" onclick="ratepayRateCalculatorAction('runtime', '<?php echo $_code ?>', '<?php echo $this->getUrl("ratepaypayment/ratenrechner/runtime", array('_secure' => true)); ?>');" value="<?php echo $this->__('lang_calculate_rate'); ?>" value="<?php echo $this->__('lang_calculate_rate'); ?>" type="button" id="<?php echo $_code ?>_Input-buttonRuntime"  class="ratepay-Input-button2">
                            </div>
                        </div>
                        <br class="ratepay-ClearFix" />
                        <div class="ratepay-ContentSwitchDiv" id="<?php echo $_code ?>_SwitchToTerm" class="ratepay-Active" style="display: none">
                            <span id="<?php echo $_code ?>_spanrate">
                                <?php echo $this->__('lang_insert_wishrate'); ?> <?php echo $this->__('lang_calculate_runtime'); ?>
                            </span>
                            <input name="" value="<?php echo $this->__('lang_calculate_runtime'); ?>" type="button" class="ratepay-Input-button ratepay-ContentSwitchInput ">
                        </div>
                        <div class="ratepay-ContentSwitchDiv"  id="<?php echo $_code ?>_SwitchToRuntime" style="display: none">
                            <span id="<?php echo $_code ?>_spanruntime" class="ratepay-active">
                                <?php echo $this->__('lang_choose_runtime'); ?> <?php echo $this->__('lang_calculate_rate'); ?>
                            </span>
                            <input name="" value="<?php echo $this->__('lang_calculate_rate'); ?>" type="button" class="ratepay-Input-button ratepay-ContentSwitchInput ">
                        </div>
                        <div id="<?php echo $_code ?>_ResultContainer"></div>
                    </div>
                </div>
                <script>
                    switchRateOrRuntime('rate', '<?php echo $_code ?>', '<?php echo $this->getSkinUrl(); ?>');
                </script>

                <br class="ratepay-ClearFix" />
            </div>
        </li>
    <?php else: ?>
        <li>
            <script>
                ratepayRateCalculatorAction('runtime', '<?php echo $_code ?>', '<?php echo $this->getUrl("ratepaypayment/ratenrechner/runtime", array('_secure' => true)); ?>');
            </script>
            <input type="hidden" id="<?php echo $_code ?>-runtime" value="<?php echo $monthAllowed['month_allowed'][0]; ?>" />
            <div id="ratepay-main-cont">
                <div id="ratepay-ContentSwitch">
                    <div class="ratepay-ChooseRuntime">
                        <div id="<?php echo $_code ?>_ResultContainer"></div>
                    </div>
                </div>
            </div>
        </li>
    <?php endif; ?>
</ul>
