<?php
/**
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

?>

<div style="border-bottom: 4px solid #DFDFDF;margin-bottom: 18px;padding-bottom: 0.25em;">
<h3>Request</h3>
<pre><?php echo $this->getRequest(); ?></pre>
</div> 

<div style="border-bottom: 4px solid #DFDFDF;margin-bottom: 18px;padding-bottom: 0.25em;">
<h3>Response</h3>
<pre><?php echo $this->getResponse(); ?></pre>
</div>
