<?php
/**
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>

<button type="button" class="scalable back" onclick="setLocation('<?php echo $this->getLogUrl(); ?>')" style="float: right;">
    <span><?php echo $this->__('Back'); ?></span>
</button>


<div style="border-bottom: 4px solid #DFDFDF;margin-bottom: 18px;padding-bottom: 0.25em;">
    <h3>Request</h3>
    <pre><?php echo $this->getRequestXml(); ?></pre>
</div> 

<div style="border-bottom: 4px solid #DFDFDF;margin-bottom: 18px;padding-bottom: 0.25em;">
    <h3>Response</h3>
    <pre><?php echo $this->getResponseXml(); ?></pre>
</div>
