<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
    $_code = $this->getMethodCode();
    $dob = $this->getDob();
    $bankData = $this->getBankData();
?>

<style>
    .sp-methods select.ratepayday {width:154px ; margin-right: 7px;}
    .sp-methods select.ratepaymonth {width: 154px ; margin-right: 7px;}
    .sp-methods select.ratepayyear {width: 154px ;}
    .sp-methods input.ratepayphone {width: 147px;}
    .sp-methods div.ratepaybirthdate {width: 476px;}
    .sp-methods .form-list .ratepayagreement {width: auto;float: none;}
    .ratepay-sandbox-notification {
        border: 2px dashed #000000;
        background-color: #ffff00;
        font-weight: bold;
        font-color: #000000;
        text-align: center;
    }
    .btn {
        -moz-user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        cursor: pointer;
        display: inline-block;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857;
        margin-bottom: 0;
        padding: 6px 12px;
        text-align: center;
        vertical-align: middle;
        white-space: nowrap;
    }
    .btn-default {
        background-color: #fff;
        border-color: #ccc;
        color: #333;
    }
    .btn-primary {
        background-color: #337ab7;
        border-color: #2e6da4;
        color: #fff;
    }
    .email_default_requirement_message {
        color: orangered;
        font-weight: bold;
        background-color: bisque;
        margin-top: 10px;
    }
</style>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($this->isSandbox()): ?>
        <li class="ratepay-sandbox-notification">
            <?php echo $this->__('Sandbox Notifcation'); ?>
        </li>
    <?php endif; ?>

    <li class="email_default_requirement_message">
        <?php echo $this->__('The email address is required for this payment method.'); ?>
    </li>

    <?php if ($this->isAdditionalFieldsNeeded()): ?>
        <li>
            <b><?php echo $this->__('Missing contact informations'); ?></b>
        </li>
    <?php endif; ?>

    <?php if ($this->isB2b()): ?>
        <li id="vatIdForm_directdebit" style="display: <?php echo ($this->isTaxvatNeeded()) ? "inline-block" : "none"; ?>">
            <label for="<?php echo $_code ?>_taxvat"><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getVatId() ?>" type="text" name="payment[<?php echo $_code ?>_taxvat]" id="<?php echo $_code ?>_taxvat" name="payment[<?php echo $_code ?>_taxvat]" class="input-text"/>
            </div>
        </li>
        <li id="vatIdLabel_directdebit" style="display: <?php echo ($this->isTaxvatNeeded()) ? "none" : "inline-block"; ?>">
            <label><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="dob-day">
                <label><?php echo $this->getVatId() ?>&nbsp;<a onclick="alterVatId('directdebit')"><?php echo $this->__('Alter') ?></a></label>
            </div>
        </li>
        <br/>
    <?php endif; ?>

    <?php if (!$this->isValidPhone()): ?>
        <li>
            <label for="<?php echo $_code ?>_phone" class="required"><em>*</em><?php echo $this->__('Phone'); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getPhone() ?>" type="text" name="payment[<?php echo $_code ?>_phone]" id="<?php echo $_code ?>_phone" name="payment[<?php echo $_code ?>_phone]" class="input-text required-entry ratepayphone"/>
            </div>
        </li>
    <?php endif; ?>

    <?php if (!$this->isB2b()): ?>
        <li id="dobForm_directdebit" style="display: <?php echo ($this->isDobSet()) ? "none" : "inline-block"; ?>">
            <label for="month" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
            <div class="input-box customer-dob ratepaydirectdebitdob" id="ratepay_directdebit_dob">
                <div class="dob-day">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Day') ?>" value="<?php if ($dob) echo substr($dob, 8, 2) ?>" name="payment[<?php echo $_code ?>_day]" id="<?php echo $_code ?>_day">
                    <label for="<?php echo $_code ?>_day"><?php echo $this->__('DD'); ?></label>
                </div><div class="dob-month">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Month') ?>" value="<?php if ($dob) echo substr($dob, 5, 2) ?>" name="payment[<?php echo $_code ?>_month]" id="<?php echo $_code ?>_month">
                    <label for="<?php echo $_code ?>_month"><?php echo $this->__('MM'); ?></label>
                </div><div class="dob-year">
                    <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Year') ?>" value="<?php if ($dob) echo substr($dob, 0, 4) ?>" name="payment[<?php echo $_code ?>_year]" id="<?php echo $_code ?>_year">
                    <label for="<?php echo $_code ?>_year"><?php echo $this->__('YYYY'); ?></label>
                </div>    <div style="display:none;" class="dob-full">
                    <input type="hidden" name="<?php echo $_code ?>_dob" id="<?php echo $_code ?>_dob">
                </div>

                <div style="display:none;" class="validation-advice"></div>
            </div>
            <script type="text/javascript">
                //&lt;![CDATA[
                var customer_dob = new Varien.RatepayDOB('.ratepaydirectdebitdob', true, '%d.%m.%y');
                //]]&gt;
            </script>
        </li>
        <li id="dobLabel_directdebit" style="display: <?php echo ($this->isDobSet()) ? "inline-block" : "none"; ?>">
            <label><?php echo $this->__('Date of Birth') ?></label>
            <div class="dob-day">
                <label><?php echo substr($dob, 8, 2) . "." . substr($dob, 5, 2) . "." . substr($dob, 0, 4) ?> <a onclick="alterDob('directdebit')"><?php echo $this->__('Alter') ?></a></label>
            </div>
        </li>
    <?php endif; ?>

    <br/>

    <ul style="border: 1px solid #BDBDBD; padding-left: 4px;">
        <li><label><?php echo $this->__('Ratepay address') ?></label></li>
        <li><label><?php echo $this->__('Creditor') ?>: <?php echo $this->__('Ratepay Creditor ID') ?></label></li>
        <li><label><?php echo $this->__('Mandate') ?>: <?php echo $this->__('Mandate Ref') ?></label></li>
    </ul>
    <br/>
    <ul>
        <li>
            <label>
                <?php echo $this->__('insert bank data'); ?>
            </label>
        </li>
        <?php if (!$this->isIbanOnly()): ?>
        <li>
            <button id="ratepay_directdebit_sepa_switch" type="button" class="btn btn-primary" onclick="switchAccountType('<?php echo $_code ?>', this)"><span><span><?php echo $this->__('SEPA Account Information') ?></span></span></button>
            <button id="ratepay_directdebit_classic_switch" type="button" class="btn btn-default" onclick="switchAccountType('<?php echo $_code ?>', this)"><span><span><?php echo $this->__('Classic Account Information') ?></span></span></button>
        </li>
        <?php endif; ?>
        <li>
            <label for="ratepay_directdebit_account_holder"><?php echo $this->__('Account holder'); ?></label>
            <div class="input-box" style="font-weight: bold">
                <?php echo $this->getAccountOwner(); ?>
            </div>
        </li>
        <li id="ratepay_directdebit_element_iban">
            <label for="ratepay_directdebit_iban" class="required"><em>*</em><?php echo $this->__('IBAN'); ?></label>
            <div class="input-box">
                <input value="<?php echo $bankData['iban']; ?>" type="text" name="payment[ratepay_directdebit_iban]" id="ratepay_directdebit_iban" class="input-text" onchange="preProcessingBankForm(this)" />
            </div>
        </li>
        <?php if ($this->getCountryCode() != 'de'): ?>
            <li id="ratepay_directdebit_element_bic">
                <label for="ratepay_directdebit_bic" class="required"><em>*</em><?php echo $this->__('SWIFT-BIC'); ?></label>
                <div class="input-box">
                    <input value="<?php echo $bankData['bic']; ?>" type="text" name="payment[ratepay_directdebit_bic]" id="ratepay_directdebit_bic" class="input-text" onchange="preProcessingBankForm(this)" />
                </div>
            </li>
        <?php endif; ?>
        <?php if (!$this->isIbanOnly()): ?>
            <li id="ratepay_directdebit_element_accountnumber" style="display: none;">
                <label for="ratepay_directdebit_account_number" class="required"><em>*</em><?php echo $this->__('Account number'); ?></label>
                <div class="input-box">
                    <input value="<?php echo $bankData['accountnumber']; ?>" type="text" name="payment[ratepay_directdebit_account_number]" id="ratepay_directdebit_account_number" class="input-text" onchange="preProcessingBankForm(this)" />
                </div>
            </li>
            <li id="ratepay_directdebit_element_bankcode" style="display: none;">
                <label for="ratepay_directdebit_bank_code_number" class="required"><em>*</em><?php echo $this->__('Bank code number'); ?></label>
                <div class="input-box">
                    <input value="<?php echo $bankData['bankcode'] ?>" type="text" name="payment[ratepay_directdebit_bank_code_number]" id="ratepay_directdebit_bank_code_number" class="input-text" onchange="preProcessingBankForm(this)" />
                </div>
            </li>
        <?php endif; ?>

        <li>
            <table>
                <tr>
                    <td style="vertical-align: top; padding-right: 5px;">
                        <input type="checkbox" class="checkbox" value="1" name="payment[<?php echo $_code ?>_agreement]" id="<?php echo $_code ?>_agreement" >
                    </td>
                    <td>
                        <span class="required ratepayagreement">
                            <?php echo $this->__('ratepay_directdebit_sepa_terms_block_1');?>
                            <?php echo $this->__('Ratepay address');?>
                            <?php echo $this->__('ratepay_directdebit_sepa_terms_block_2');?>
                            <a target="_blank" href="<?php echo $this->getPrivacyPolicyUrl(); ?>"><?php echo $this->__('Ratepay Data Privacy Policy');?></a>
                            <?php echo $this->__('ratepay_directdebit_sepa_terms_block_3');?>
                        </span>
                    </td>
                </tr><tr>
                    <td></td>
                    <td>
                        <br/>
                        <span style="font-weight:bold;"><?php echo $this->__('ratepay_directdebit_sepa_notice_block_1');?></span>
                        <br/>
                        <?php echo $this->__('ratepay_directdebit_sepa_notice_block_2');?>
                        <br/>
                        <?php echo $this->__('ratepay_directdebit_sepa_notice_block_3');?>
                    </td>
                </tr>
            </table>
        </li>
        <script type="text/javascript">
            initPaymentMethodListeners();
        </script>
</ul>