<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
$_code = $this->getMethodCode();
$dob = $this->getDob();
$calculationData = $this->getInstallmentCalculationData();
$monthAllowed = $calculationData['monthAllowed'];
$bankData = $this->getBankData();
$firstday = $this->getFirstday();

/* @var \RatePAY_Ratepaypayment_Helper_Data $_paymentHelper */
$_paymentHelper = Mage::helper('ratepaypayment');
?>

<style>

    .sp-methods select.ratepayday {
        width:154px ; margin-right: 7px;
    }

    .sp-methods select.ratepaymonth {
        width: 154px ; margin-right: 7px;
    }

    .sp-methods select.ratepayyear {
        width: 154px ;
    }

    .sp-methods input.ratepayphone {
        width: 147px;
    }

    .sp-methods div.ratepaybirthdate {
        width: 476px;
    }

    /* RatePAY Calculator */
    .rpContainer {
        width: 100%;
        margin: 10px 0;
    }
    .sepablock li {
        list-style-type: none;
    }
    .row {
        margin: 5px 0;
    }
    .col-md-5 {
        width: calc(50% - 6px);
        margin: 0 3px;
        float: left;
    }
    .panel {
        display: block;
        background: #fff;
        margin-bottom: 20px;
        background-color: #fff;
        border: 1px solid transparent;
        border-radius: 3px;
        box-sizing: border-box;
        box-shadow: 0 1px 1px rgba(0,0,0,0.05);
    }
    .panel-heading {
        border-color: #ddd;
        border-bottom: 1px solid #ddd;
        border-top-right-radius: 3px;
        border-top-left-radius: 3px;
        color: #333;
        background-color: #f5f5f5;
    }
    .panel-default {
        border-color: #ddd;
    }
    .text-center {
        padding: 10px 0px;
        border-top: 1px solid #ddd;
        text-align: center;
    }
    .panel-body {
        padding: 15px;
        box-sizing: border-box;
        min-height: 68px;
    }
    .btn {
        padding: 2px 10px 2px 10px;
        padding: .125rem .625rem .125rem .625rem;
        line-height: 32px;
        line-height: 2rem;
        border-radius: 3px;
        background-clip: padding-box;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        font-size: 14px;
        font-size: .875rem;
        background-color: #fff;
        -webkit-font-smoothing: inherit;
        display: inline-block;
        position: relative;
        font-weight: bold;
        text-decoration: none;
        text-align: left;
        cursor: pointer;
        border: 1px solid #dadae5;
        color: #5f7285;
    }
    .btn-group {
        position: relative;
        display: inline-block;
        vertical-align: middle;
        box-sizing: border-box;
    }
    .btn-group-justified {
        display: table;
        width: 100%;
        table-layout: fixed;
        border-collapse: separate;
    }
    .btn-group-justified>.btn, .btn-group-justified>.btn-group {
        float: none;
        display: table-cell;
        width: 1%;
        vertical-align: middle;
        position: relative;
    }
    #ratepay_rate-rate {
        width: inherit;
    }
    .rp-link {
        margin-left: 20px;
        cursor: pointer;
    }
    .rp-details-icon {
        float: right;
        padding: 5px;
        height: 20px;
    }


    /* RatePAY Calculator Result */
    .rp-table-striped {
        width: 100%;
    }
    * {
        box-sizing: border-box;
    }
    .text-uppercase {
        text-transform: uppercase;
    }
    .text-center {
        padding: 10px 0px;
        border-top: 1px solid #ddd;
        text-align: center;
    }
    .warning {
        background-color: #fcf8e3;
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        padding: 7px 0px;
    }
    .rp-menue, .rp-installment-plan-details, .rp-installment-plan-no-details {
        border-bottom: 1px solid #ddd;
        width: 100%;
        margin: 0px 3px;
        padding: 13px 6px;
    }
    #rp-installment-plan-details {
        display: none;
    }
    #rp-installment-plan-no-details {
        display: block;
    }
    .rp-installment-plan-details:nth-child(odd) {
        background-color: #f9f9f9;
    }
    .rp-installment-plan-title {
        float: left;
    }
    .text-right {
        text-align: right;
    }
    .rp-installment-plan-description {
        display: none;
        position: absolute;
        margin-top: -5px;
    }
    .small {
        font-size: 85%;
    }
    .rp-term-buttons {
        display: inline-grid;
        width: 100%;
    }
    .rp-term-buttons>button {
        padding: 3px 0;
    }
    .ratepay-input-button {
        padding: 3px 5px;
    }
    .rp-term-select {
        width: 100%;
    }
    .rp-time-buttons {
        display: inline-grid;
        grid-template-columns: 7% auto 33%;
        width: 100%;
    }
</style>

<style>
    .sp-methods select.ratepayday {width:154px ; margin-right: 7px;}
    .sp-methods select.ratepaymonth {width: 154px ; margin-right: 7px;}
    .sp-methods select.ratepayyear {width: 154px ;}
    .sp-methods input.ratepayphone {width: 147px;}
    .sp-methods div.ratepaybirthdate {width: 476px;}
    .sp-methods .form-list .ratepayagreement {width: auto;float: none;}
    .ratepay-sandbox-notification {
        border: 2px dashed #000000;
        background-color: #ffff00;
        font-weight: bold;
        font-color: #000000;
        text-align: center;
    }
    .btn {
        -moz-user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        cursor: pointer;
        display: inline-block;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857;
        margin-bottom: 0;
        padding: 6px 12px;
        text-align: center;
        vertical-align: middle;
        white-space: nowrap;
    }
    .btn-default {
        background-color: #fff;
        border-color: #ccc;
        color: #333;
    }
    .email_default_requirement_message {
        color: orangered;
        font-weight: bold;
        background-color: bisque;
        margin-top: 10px;
    }
</style>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <input type="hidden" id="ratepay_payment_firstday_<?php echo $_code ?>" value="28">

    <?php if ($this->isSandbox()): ?>
        <li class="ratepay-sandbox-notification">
            <?php echo $this->__('Sandbox Notifcation'); ?>
        </li>
    <?php endif; ?>

    <li class="email_default_requirement_message">
        <?php echo $this->__('The email address is required for this payment method.'); ?>
    </li>

    <?php if ($this->isAdditionalFieldsNeeded()): ?>
        <li>
            <b><?php echo $this->__('Missing contact informations'); ?></b>
        </li>
    <?php endif; ?>

    <?php if ($this->isB2b()): ?>
        <li id="vatIdForm_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "inline-block" : "none"; ?>">
            <label for="<?php echo $_code ?>_taxvat"><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getVatId() ?>" type="text" name="payment[<?php echo $_code ?>_taxvat]" id="<?php echo $_code ?>_taxvat" class="input-text"/>
            </div>
        </li>
        <li id="vatIdLabel_rate" style="display: <?php echo ($this->isTaxvatNeeded()) ? "none" : "inline-block"; ?>">
            <label><?php echo $this->__('Tax/VAT number') . "&nbsp;" . $this->getCompany(); ?></label>
            <div class="dob-day">
                <label><?php echo $this->getVatId() ?>&nbsp;<a onclick="alterVatId('rate')"><?php echo $this->__('Alter') ?></a></label>
            </div>
        </li>
        <br/>
    <?php endif; ?>

    <?php if (!$this->isValidPhone()): ?>
        <li>
            <label for="<?php echo $_code ?>_phone"><?php echo $this->__('Phone'); ?></label>
            <div class="input-box">
                <input value="<?php echo $this->getPhone() ?>" type="text" name="payment[<?php echo $_code ?>_phone]" id="<?php echo $_code ?>_phone" class="input-text ratepayphone"/>
            </div>
        </li>
    <?php endif; ?>

    <li id="dobForm_<?php echo $_code ?>" style="display: <?php echo ($this->isDobSet()) ? "none" : "inline-block"; ?>">
        <label for="month" class="required"><em>*</em><?php echo $this->__('Date of Birth') ?></label>
        <div class="input-box customer-dob ratepaydob_<?php echo $_code ?>" id="">
            <div class="dob-day">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Day') ?>" value="<?php if ($dob) echo substr($dob, 8, 2) ?>" name="payment[<?php echo $_code ?>_day]" id="<?php echo $_code ?>_day">
                <label for="<?php echo $_code ?>_day">DD</label>
            </div>
            <div class="dob-month">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Month') ?>" value="<?php if ($dob) echo substr($dob, 5, 2) ?>" name="payment[<?php echo $_code ?>_month]" id="<?php echo $_code ?>_month">
                <label for="<?php echo $_code ?>_month">MM</label>
            </div>
            <div class="dob-year">
                <input type="text" class="input-text validate-custom" title="<?php echo $this->__('Year') ?>" value="<?php if ($dob) echo substr($dob, 0, 4) ?>" name="payment[<?php echo $_code ?>_year]" id="<?php echo $_code ?>_year">
                <label for="<?php echo $_code ?>_year">YYYY</label>
            </div>
            <div style="display:none;" class="dob-full">
                <input type="hidden" name="<?php echo $_code ?>_dob" id="<?php echo $_code ?>_dob">
            </div>

            <div style="display:none;" class="validation-advice"></div>
        </div>
        <script type="text/javascript">
            //&lt;![CDATA[
            var customer_dob = new Varien.RatepayDOB('.ratepaydob_<?php echo $_code ?>', true, '%d.%m.%y');
            //]]&gt;
        </script>
    </li>
    <li id="dobLabel_<?php echo $_code ?>" style="display: <?php echo ($this->isDobSet()) ? "inline-block" : "none"; ?>">
        <label><?php echo $this->__('Date of Birth') ?></label>
        <div class="dob-day">
            <label><?php echo substr($dob, 8, 2) . "." . substr($dob, 5, 2) . "." . substr($dob, 0, 4) ?> <a onclick="alterDob('rate<?php echo 'ratepay_rate0' === $_code ? '0' : '';?>')"><?php echo $this->__('Alter') ?></a></label>
        </div>
    </li>

    <?php if (count($monthAllowed) > 1): ?>
        <li>
            <div class="rpContainer">
                <div class="row">
                    <div class="col-md-10">
                        <?php
                        echo $this->__('rp_calculation_intro_part1');
                        echo $this->__('rp_calculation_intro_part2');
                        echo $this->__('rp_calculation_intro_part3');
                        ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <div class="panel panel-default">
                            <div class="panel-heading text-center" id="firstInput">
                                <h3><?php echo $this->__('rp_runtime_title'); ?></h3>
                                <?php echo $this->__('rp_runtime_description'); ?>
                            </div>
                            <div class="panel-body">
                                <?php
                                $currency =  $_paymentHelper->isEnterpriseEdition() ? $_paymentHelper->getCurrencyAmountForRewardPoints() : 0;

                                $maxButtons = 9;

                                $jsCommand = "ratepayRateCalculatorAction(" .
                                    "'runtime', " .
                                    "'{$_code}', " .
                                    "'" . Mage::helper('adminhtml')->getUrl("adminhtml/ratepaypayment_ratenrechnerbackend/runtime", array('_secure' => true)) . " ', " .
                                    "'" . Mage::getSingleton('core/session')->getFormKey() . "', " .
                                    "'{$currency}', " .
                                    "this.value);";

                                if (count($monthAllowed) > $maxButtons) :
                                ?>
                                    <select class="rp-term-select" onchange="<?php echo $jsCommand; ?>">
                                        <option disabled selected>
                                            <?php echo $this->__('please_choose') ?>
                                        </option>
                                        <?php foreach ($monthAllowed AS $month) : ?>
                                            <option value="<?php echo $month; ?>">
                                                <?php echo $month; ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php else : ?>
                                    <div class="rp-term-buttons" role="group" aria-label="..." style="grid-template-columns: repeat(<?php echo min(3, count($monthAllowed)) ?>, <?php echo 100/min(3, count($monthAllowed)) ?>%)">
                                    <?php foreach ($monthAllowed AS $month) : ?>
                                        <button type="button"
                                                onclick="<?php echo $jsCommand; ?>"
                                                value="<?php echo $month; ?>"
                                                id="piRpInput-buttonMonth-<?php echo $month; ?>"
                                                role="group"><?php echo $month; ?></button>
                                    <?php endforeach; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="panel panel-default">
                            <div class="panel-heading text-center" id="secondInput">
                                <h3><?php echo $this->__('rp_rate_title'); ?></h3>
                                <?php echo $this->__('rp_rate_description'); ?>
                            </div>

                            <div class="panel-body">
                                <div class="input-group input-group-sm rp-time-buttons">
                                    <span class="input-group-addon">&euro;</span>
                                    <input type="text" id="<?php echo $_code ?>-rate" class="form-control" aria-label="Amount" />
                                    <span class="input-group-btn">
                                        <input onclick="ratepayRateCalculatorAction(
                                                'rate',
                                                '<?php echo $_code ?>',
                                                '<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/ratepaypayment_ratenrechnerbackend/rate", array('_secure' => true)); ?>',
                                                '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>');"
                                           value="<?php echo $this->__('rp_calculate_rate'); ?>"
                                           id="<?php echo $_code ?>_Input-button"
                                           class="ratepay-input-button"
                                           type="button">
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br style="clear: both;" />
                <div id="ratepay-main-cont">
                    <div id="ratepay-ContentSwitch">
                        <div class="ratepay-ChooseRuntime">
                            <div id="<?php echo $_code ?>_ResultContainer"></div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    <?php else: ?>
        <li>
            <script>
                ratepayRateCalculatorAction(
                    'runtime',
                    '<?php echo $_code ?>',
                    '<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/ratepaypayment_ratenrechnerbackend/runtime", array('_secure' => true)); ?>',
                    '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>',
                    '<?php echo $_paymentHelper->isEnterpriseEdition() ? $_paymentHelper->getCurrencyAmountForRewardPoints() : 0; ?>'
                );
            </script>
            <input type="hidden" id="<?php echo $_code ?>-runtime" value="<?php echo $monthAllowed[0]; ?>" />
            <div id="ratepay-main-cont">
                <div id="ratepay-ContentSwitch">
                    <div class="ratepay-ChooseRuntime">
                        <div id="<?php echo $_code ?>_ResultContainer"></div>
                    </div>
                </div>
            </div>
        </li>
    <?php endif; ?>
    <input type="hidden" id="ratepay_installment_rate_<?php echo $_code ?>" value="<?php echo ('ratepay_rate0' === $_code) ? 0 : 1; ?>">
    <input type="hidden" id="ratepay_installment_url_rate_<?php echo $_code ?>" value="<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/ratepaypayment_ratenrechnerbackend/rate", array('_secure' => true)); ?>">
    <input type="hidden" id="ratepay_installment_url_runtime_<?php echo $_code ?>" value="<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/ratepaypayment_ratenrechnerbackend/runtime", array('_secure' => true)); ?>">
    <input type="hidden" id="ratepay_rate_method_invoice_<?php echo $_code ?>" name="payment[<?php echo $_code ?>_method_invoice]" value="<?php echo is_array($firstday) || $firstday == '2' ? 0 : 1;  ?>">

    <div class="sepablock" id="ratepay_rate_sepa_block_<?php echo $_code ?>" style="display:none">
        <?php if (is_array($firstday) || $firstday == '2'): ?>
            <li>
                <hr />
            </li>

            <li class="<?php echo $_code ?>_sepa_element">
                <ul style="border: 1px solid #BDBDBD; padding-left: 4px;">
                    <li><label><?php echo $this->__('Ratepay address') ?></label></li>
                    <li><label><?php echo $this->__('Creditor') ?>: <?php echo $this->__('Ratepay Creditor ID') ?></label></li>
                    <li><label><?php echo $this->__('Mandate') ?>: <?php echo $this->__('Mandate Ref') ?></label></li>
                </ul>
            </li>

            <li class="<?php echo $_code ?>_sepa_element">
                <label for="ratepay_rate_account_holder"><?php echo $this->__('Account holder'); ?></label>
                <div class="input-box" style="font-weight: bold">
                    <?php echo $this->getAccountOwner(); ?>
                </div>
            </li>
            <li id="ratepay_rate_element_iban_<?php echo $_code ?>" class="<?php echo $_code ?>_sepa_element">
                <label for="ratepay_rate_iban" class="required"><em>*</em><?php echo $this->__('IBAN'); ?></label>
                <div class="input-box">
                    <input value="<?php echo $bankData['iban']; ?>" type="text" name="payment[<?php echo $_code ?>_iban]" id="ratepay_rate_iban_<?php echo $_code ?>" class="ratepay_rate_sepa_form" onkeyup="isIban(this, '<?php echo $_code ?>')" />
                </div>
            </li>
            <?php if ('ratepay_rate0' !== $_code) : ?>
                <li id="ratepay_rate_element_bankcode_<?php echo $_code ?>" class="<?php echo $_code ?>_sepa_element" style="display:none;">
                    <label for="ratepay_rate_bank_code_number" class="required"><em>*</em><?php echo $this->__('Bank code number'); ?></label>
                    <div class="input-box">
                        <input value="<?php echo $bankData['bankcode'] ?>" type="text" name="payment[<?php echo $_code ?>_bank_code_number]" id="<?php echo $_code ?>_bank_code_number" class="ratepay_rate_sepa_form" onchange="preProcessingBankForm(this)" />
                    </div>
                </li>
            <?php endif ?>

            <li class="<?php echo $_code ?>_sepa_element">
                <table>
                    <tbody id="ratepay_rate_sepa_agreement_<?php echo $_code ?>">
                    <tr>
                        <td style="vertical-align: top; padding-right: 5px;">
                            <input type="checkbox" class="checkbox ratepay_rate_sepa_form" value="1" name="payment[<?php echo $_code ?>_agreement]" id="<?php echo $_code ?>_agreement" >
                        </td>
                        <td>
                                <span class="required ratepayagreement">
                                    <?php echo $this->__('ratepay_directdebit_sepa_terms_block_1');?>
                                    <?php echo $this->__('Ratepay address');?>
                                    <?php echo $this->__('ratepay_directdebit_sepa_terms_block_2');?>
                                    <a target="_blank" href="<?php echo $this->getPrivacyPolicyUrl(); ?>"><?php echo $this->__('Ratepay Data Privacy Policy');?></a>
                                    <?php echo $this->__('ratepay_directdebit_sepa_terms_block_3');?>
                                </span>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <br/>
                            <span></span>
                            <span style="font-weight:bold; cursor: hand;"><?php echo $this->__('ratepay_directdebit_sepa_notice_block_1');?></span>
                            <br/>
                            <?php echo $this->__('ratepay_directdebit_sepa_notice_block_2');?>
                            <br/>
                            <?php echo $this->__('ratepay_directdebit_sepa_notice_block_3');?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </li>

            <?php if (is_array($firstday)): ?>
                <li>
                    <a id="ratepay_rate_method_switch_invoice_<?php echo $_code ?>"
                       style="cursor: pointer;"
                       onclick="switchRatePaymentMethod(
                           this,
                           '<?php echo $_code ?>',
                           '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>',
                           '<?php echo $_paymentHelper->isEnterpriseEdition() ? $_paymentHelper->getCurrencyAmountForRewardPoints() : 0; ?>');">
                        Ich möchte die Ratenzahlung selbst vornehmen und nicht per Lastschrift begleichen
                    </a>
                    <a id="ratepay_rate_method_switch_directdebit_<?php echo $_code ?>"
                       style="cursor: pointer; display: none;"
                       onclick="switchRatePaymentMethod(
                           this,
                           '<?php echo $_code ?>',
                           '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>',
                           '<?php echo $_paymentHelper->isEnterpriseEdition() ? $_paymentHelper->getCurrencyAmountForRewardPoints() : 0; ?>');">
                        Ich möchte die Ratenzahlung per Lastschrift begleichen
                    </a>
                </li>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
        initPaymentMethodListeners();
    </script>
</ul>
