<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2015 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<style>
    .pirpmain-cont {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
    .pirpmain-cont h2 {
        font-size: small;
    }
    /*table#piInstallmentTerms {
        margin: 0 auto -10px auto;
        font-size: smaller;
    }*/
</style>

<?php if ($this->getRatepayMethodCode() == "ratepay_rate"): ?>
    <div class="pirpmain-cont">
        <?php $this->showRateResultHtml(); ?>
    </div>
<?php endif; ?>