<?php
/**
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>

<?php
/** @var RatePAY_Ratepaypayment_Block_Checkout_Installmentplan $block */
$block = $this;
$method = $block->getRatepayMethodCode();
$result = $block->getDetails();
?>

<?php if (strstr($method, "ratepay_rate")): ?>
    <div id="ratepay-main-cont">
        <style>
            .rp-installment-plan-details:hover #totalAmount { display: block; }
            .rp-installment-plan-no-details:hover #rate2 { display: block; }
            .rp-installment-plan-details:hover #lastRate { display: block; }
            .rp-installment-plan-details:hover #rate { display: block; }
            .rp-installment-plan-details:hover #interestAmount { display: block; }
            .rp-installment-plan-details:hover #interestRate { display: block; }
            .rp-installment-plan-details:hover #annualPercentageRate { display: block; }
            .rp-installment-plan-details:hover #serviceCharge { display: block; }
            .rp-installment-plan-details:hover #amount { display: block; }
            #rp-hide-installment-plan-details_<?php echo $method; ?> { display: none; }
            #rp-show-installment-plan-details_<?php echo $method; ?> { display: block; }
            #rp-installment-plan-details_<?php echo $method; ?> { display: none; }
            #rp-installment-plan-no-details_<?php echo $method; ?> { display: block; }
        </style>
        <div class="rp-table-striped">
            <div>
                <div class="text-center text-uppercase" colspan="2">
                    <?php echo $block->__('rp_personal_calculation'); ?>
                </div>
            </div>

            <div class="rp-menue">
                <div colspan="2" class="small text-right">
                    <a class="rp-link" id="rp-show-installment-plan-details_' . $method . '" onclick="changeDetails('<?php echo $method; ?>')">
                        Zeige Details
                        <img src="<?php echo Mage::getDesign()->getSkinUrl('images/ratepay/icon-enlarge.png'); ?>" class="rp-details-icon" />
                    </a>
                    <a class="rp-link" id="rp-hide-installment-plan-details_<?php echo $method; ?>" onclick="changeDetails('<?php echo $method; ?>')">
                        Schließe Details
                        <img src="<?php echo Mage::getDesign()->getSkinUrl('images/ratepay/icon-shrink.png'); ?>" class="rp-details-icon" />
                    </a>
                </div>
            </div>
            <div id="rp-installment-plan-details_<?php echo $method; ?>">
                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_cash_payment_price'); ?>
                        <p id="amount" class="rp-installment-plan-description small">
                            <?php echo $block->__('rp_mouseover_cash_payment_price'); ?>
                        </p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['amount']; ?> &euro;
                    </div>
                </div>
                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_service_charge'); ?>
                        <p id="serviceCharge" class="rp-installment-plan-description small">
                            <?php echo $block->__('rp_mouseover_service_charge'); ?>
                        </p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['serviceCharge']; ?> &euro;
                    </div>
                </div>

                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_effective_rate'); ?>
                        <p id="annualPercentageRate" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_effective_rate'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['annualPercentageRate']; ?> %
                    </div>
                </div>

                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_debit_rate'); ?>
                        <p id="interestRate" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_debit_rate'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['interestRate']; ?> %
                    </div>
                </div>

                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_interest_amount'); ?>
                        <p id="interestAmount" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_interest_amount'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['interestAmount']; ?> &euro;
                    </div>
                </div>

                <div class="rp-installment-plan-details">
                    <div colspan="2"></div>
                </div>


                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $result['numberOfRates']; ?> <?php echo $block->__('rp_duration_month'); ?>
                        <p id="rate" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_duration_month'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['rate']; ?> &euro;
                    </div>
                </div>

                <div class="rp-installment-plan-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $block->__('rp_last_rate'); ?>
                        <p id="lastRate" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_last_rate'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['lastRate']; ?> &euro;
                    </div>
                </div>
            </div>
            <div id="rp-installment-plan-no-details_<?php echo $method; ?>">
                <div class="rp-installment-plan-no-details">
                    <div class="rp-installment-plan-title">
                        <?php echo $result['numberOfRatesFull']; ?> <?php echo $block->__('rp_duration_month'); ?>
                        <p id="rate2" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_duration_month'); ?></p>
                    </div>
                    <div class="text-right">
                        <?php echo $result['rate']; ?> &euro;
                    </div>
                </div>
            </div>
            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $block->__('rp_total_amount'); ?>
                    <p id="totalAmount" class="rp-installment-plan-description small"><?php echo $block->__('rp_mouseover_total_amount'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['totalAmount']; ?> &euro;
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var elements = document.getElementsByClassName('rp-link');
        var i;
        for (i = 0; i < elements.length; i++) {
            if (i == elements.length - 2) {
                elements[i].style.display = 'none';
            }
        }
    </script>
<?php endif; ?>