<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category RatePAY
 * @package RatePAY_Ratepaypayment
 * @copyright Copyright (c) 2019 RatePAY GmbH (https://www.ratepay.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $this RatePAY_Ratepaypayment_Block_Checkout_InstallmentplanDetails */
$result = $this->getData('result');
$method = $this->getData('method');
$notification = $this->getData('code');
?>

<style>
    .rp-installment-plan-details:hover #totalAmount { display: block; }
    .rp-installment-plan-no-details:hover #rate2 { display: block; }
    .rp-installment-plan-details:hover #lastRate { display: block; }
    .rp-installment-plan-details:hover #rate { display: block; }
    .rp-installment-plan-details:hover #interestAmount { display: block; }
    .rp-installment-plan-details:hover #interestRate { display: block; }
    .rp-installment-plan-details:hover #annualPercentageRate { display: block; }
    .rp-installment-plan-details:hover #serviceCharge { display: block; }
    .rp-installment-plan-details:hover #amount { display: block; }
    #rp-hide-installment-plan-details_<?php echo $method; ?> { display: none; }
    #rp-show-installment-plan-details_<?php echo $method; ?> { display: block; }
    #rp-installment-plan-details_<?php echo $method; ?> { display: none; }
    #rp-installment-plan-no-details_<?php echo $method; ?> { display: block; }
</style>

<?php if (!empty($this->_errors)) { ?>
    <div class='pirperror'>
        <?php
            foreach ($this->_errors as $error) {
                echo $error->title . ': <br/>' . $error->message;
            }
        ?>
    </div>
<?php
   } else {
?>
    <div class="rp-table-striped">
        <div>
            <div class="text-center text-uppercase" colspan="2">
                <?php echo  $this->__('rp_personal_calculation'); ?>
            </div>
        </div>

        <?php if (!is_null($notification)) { ?>
            <div>
                <div class="warning small text-center" colspan="2">
                    <?php echo $this->__('rp_reason_code_translation_' . $notification); ?>
                    <br/>
                </div>
            </div>
        <?php } ?>

        <div class="rp-menue">
            <div colspan="2" class="small text-right">
                <a class="rp-link" id="rp-show-installment-plan-details_<?php echo $method; ?>" onclick="changeDetails('<?php echo $method; ?>')">
                    Zeige Details
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/ratepay/icon-enlarge.png'); ?>" class="rp-details-icon" />
                </a>
                <a class="rp-link" id="rp-hide-installment-plan-details_<?php echo $method; ?>" onclick="changeDetails('<?php echo $method; ?>')">
                    Schließe Details
                    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/ratepay/icon-shrink.png'); ?>" class="rp-details-icon" />
                </a>
            </div>
        </div>
        <div id="rp-installment-plan-details_<?php echo $method; ?>">
            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_cash_payment_price'); ?>
                    <p id="amount" class="rp-installment-plan-description small">
                        <?php echo $this->__('rp_mouseover_cash_payment_price') ?>
                    </p>
                </div>
                <div class="text-right">
                    <?php echo $result['amount']; ?> &euro;
                </div>
            </div>
            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_service_charge'); ?>
                    <p id="serviceCharge" class="rp-installment-plan-description small">
                        <?php echo $this->__('rp_mouseover_service_charge'); ?>
                    </p>
                </div>
                <div class="text-right">
                    <?php echo $result['serviceCharge']; ?> &euro;
                </div>
            </div>

            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_effective_rate'); ?>
                    <p id="annualPercentageRate" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_effective_rate'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['annualPercentageRate']; ?> %
                </div>
            </div>

            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_debit_rate'); ?>
                    <p id="interestRate" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_debit_rate'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['interestRate']; ?> %
                </div>
            </div>

            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_interest_amount'); ?>
                    <p id="interestAmount" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_interest_amount'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['interestAmount']; ?> &euro;
                </div>
            </div>

            <div class="rp-installment-plan-details">
                <div colspan="2"></div>
            </div>


            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $result['numberOfRates'] . ' ' . $this->__('rp_duration_month'); ?>
                    <p id="rate" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_duration_month'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['rate']; ?> &euro;
                </div>
            </div>

            <div class="rp-installment-plan-details">
                <div class="rp-installment-plan-title">
                    <?php echo $this->__('rp_last_rate'); ?>
                    <p id="lastRate" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_last_rate'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['lastRate']; ?> &euro;
                </div>
            </div>
        </div>
        <div id="rp-installment-plan-no-details_<?php echo $method; ?>">
            <div class="rp-installment-plan-no-details">
                <div class="rp-installment-plan-title">
                    <?php echo $result['numberOfRatesFull'] . ' ' . $this->__('rp_duration_month'); ?>
                    <p id="rate2" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_duration_month'); ?></p>
                </div>
                <div class="text-right">
                    <?php echo $result['rate']; ?> &euro;
                </div>
            </div>
        </div>
        <div class="rp-installment-plan-details">
            <div class="rp-installment-plan-title">
                <?php echo $this->__('rp_total_amount'); ?>
                <p id="totalAmount" class="rp-installment-plan-description small"><?php echo $this->__('rp_mouseover_total_amount'); ?></p>
            </div>
            <div class="text-right">
                <?php echo $result['totalAmount']; ?> &euro;
            </div>
        </div>
    </div>
<?php
   }
?>